## Aggregate August Raw Data

In [1]:
# import packages
import pandas as pd
import numpy as np

In [2]:
# read in csv and pull up first 5 rows
bp_aug = pd.read_csv('aug_raw_data.csv')
bp_aug.head()

/Users/christina.caddel/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,29,30,31,32,33,34,35,36,37) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Funnel Publisher           Hook     Mega Micro Category Campaign  \
0  Awareness  Facebook  MULTISHOWCASE  Compose            NaN       EG   
1  Awareness  Facebook  MULTISHOWCASE  Compose            NaN       EG   
2  Awareness  Facebook  MULTISHOWCASE    Dwell            NaN       EG   
3  Awareness  Facebook  MULTISHOWCASE    Dwell            NaN       EG   
4  Awareness  Facebook  MULTISHOWCASE     Make            NaN       EG   

  Targ/aud/pin Keyword Start Date    MAID     ...      Bounce Rate  Reg Rate  \
0     Interest     NaN    7/17/18  111970     ...           93.63%     0.21%   
1     Interest     NaN    7/17/18  111970     ...           93.63%     0.21%   
2     Interest     NaN    7/17/18  111971     ...           93.90%     0.31%   
3     Interest     NaN    7/17/18  111971     ...           93.90%     0.31%   
4     Interest     NaN    7/17/18  111973     ...           94.12%     0.29%   

    CAC (Reg) Sub Rate CAC (Sub)   Subs/Reg Rate Unnamed: 38 Unnamed: 39  \
0     $592.28   0.000%     $0.00           0.00%         NaN         NaN   
1     $719.15   0.000%     $0.00           0.00%         NaN         NaN   
2     $156.17   0.000%     $0.00           0.00%         NaN         NaN   
3     $210.11   0.000%     $0.00           0.00%         NaN         NaN   
4     $202.14   0.000%     $0.00           0.00%         NaN         NaN   

  Unnamed: 40  Unnamed: 41  
0         NaN          NaN  
1         NaN          NaN  
2         NaN          NaN  
3         NaN          NaN  
4         NaN          NaN  

[5 rows x 42 columns]

In [3]:
# pull up dataset info
bp_aug.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1031023 entries, 0 to 1031022
Data columns (total 42 columns):
Funnel                         106109 non-null object
Publisher                      106109 non-null object
Hook                           106109 non-null object
Mega                           106109 non-null object
Micro Category                 97672 non-null object
Campaign                       106109 non-null object
Targ/aud/pin                   106109 non-null object
Keyword                        79772 non-null object
Start Date                     106109 non-null object
MAID                           106109 non-null object
Video v Static                 106109 non-null object
Impressions with Video View    106109 non-null float64
Week Start                     106109 non-null object
Reporting Month                106109 non-null object
Reporting Period               106109 non-null object
Placement                      106109 non-null object
Creative                

In [4]:
# investigate column values in 'Micro Category'
bp_aug['Micro Category'].unique()

array([nan, 'None', 'Embroidery', 'Cake Decorating', 'Cooking', 'Family',
       'Food & Cooking', 'Other', 'Woodworking', 'Home Decor', 'Drawing',
       'Quilting', 'Move', 'Painting', 'Compose', 'Knitting', 'Sewing',
       'Stitch', 'Paper Crafts', 'Jewelry', 'Yoga', 'Gardening', 'Dance',
       'Baking', 'Photography', 'Make', 'Crocheting', 'LauriKranz',
       'Crochet', 'Sew', 'CakeDec', 'Cook', 'All', 'Photo', 'Emb', 'Knit',
       'Fit', 'Paint', 'Draw', 'Home', 'Quilt', 'Bake', 'Wood', 'Jewel',
       'Paper', 'Cake', 'TRIAL', 'TiffanieTurner', 'Scrapbook', 'TBD',
       'Fam', 'Food'], dtype=object)

In [5]:
# clean up 'None' values by replacing with nans and validate
bp_aug['Micro Category'] = bp_aug['Micro Category'].replace(['None', np.nan])
bp_aug['Micro Category'].unique()

array([nan, 'Embroidery', 'Cake Decorating', 'Cooking', 'Family',
       'Food & Cooking', 'Other', 'Woodworking', 'Home Decor', 'Drawing',
       'Quilting', 'Move', 'Painting', 'Compose', 'Knitting', 'Sewing',
       'Stitch', 'Paper Crafts', 'Jewelry', 'Yoga', 'Gardening', 'Dance',
       'Baking', 'Photography', 'Make', 'Crocheting', 'LauriKranz',
       'Crochet', 'Sew', 'CakeDec', 'Cook', 'All', 'Photo', 'Emb', 'Knit',
       'Fit', 'Paint', 'Draw', 'Home', 'Quilt', 'Bake', 'Wood', 'Jewel',
       'Paper', 'Cake', 'TRIAL', 'TiffanieTurner', 'Scrapbook', 'TBD',
       'Fam', 'Food'], dtype=object)

#### Are the values in the keyword column (listed below) accurate?

In [6]:
# investigate column values in 'keyword'
bp_aug['Keyword'].unique()
# No misrepresented nans

array([nan, 'Tru-View', 'Bumpers', 'BMM', 'E', 'EG', 'JamesWorsham',
       'Res', 'AngelaWalters', 'JordanDewilde', 'Sewing', 'KristyGlass',
       'NickiSizemore', '111882', 'TruView', '112800', '112799', '112804',
       '112803', '112801', '112802', 'Search', '113761', 'Feed', '111894',
       '111937', '113010', '113009', '113011', '113013', '113012',
       '113014', 'All', '111964', '111965', '112294', '111940', '111955',
       '111961', '111962', '111954', '111966', '111958', '111922',
       '111884'], dtype=object)

#### Why all the nans in Creative, Clicks, Views, Completed Views, and Conversions?

In [7]:
# amount of nulls in 'Creative','Clicks', 'Views', 'Completed Views','Conversions'
cols = ['Creative','Clicks','Views','Completed Views','Conversions']
for col in cols:
    print(bp_aug[col].isnull().sum())

976797
932219
934045
934686
934310


In [8]:
#investigate random columns at the end
list(bp_aug.columns.values)

['Funnel',
 'Publisher',
 'Hook',
 'Mega',
 'Micro Category',
 'Campaign',
 'Targ/aud/pin',
 'Keyword',
 'Start Date',
 'MAID',
 'Video v Static',
 'Impressions with Video View',
 'Week Start',
 'Reporting Month',
 'Reporting Period',
 'Placement',
 'Creative',
 'Date',
 'Cost',
 'Impressions',
 'Clicks',
 'Views',
 'Completed Views',
 'Conversions',
 'Sessions',
 'New Sessions',
 'Bounce',
 'Register',
 'Subscribe',
 'CTR',
 'CPC',
 'VCR',
 'Bounce Rate',
 'Reg Rate',
 '  CAC (Reg)',
 'Sub Rate',
 'CAC (Sub)',
 '  Subs/Reg Rate',
 'Unnamed: 38',
 'Unnamed: 39',
 'Unnamed: 40',
 'Unnamed: 41']

In [9]:
# drop those, and CTR - Subs/Reg Rate and validate
bp_aug = bp_aug.drop(columns=['Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41','CTR','CPC','VCR','Bounce Rate',
                             'Reg Rate','  CAC (Reg)','Sub Rate','CAC (Sub)','  Subs/Reg Rate'])
bp_aug.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1031023 entries, 0 to 1031022
Data columns (total 29 columns):
Funnel                         106109 non-null object
Publisher                      106109 non-null object
Hook                           106109 non-null object
Mega                           106109 non-null object
Micro Category                 1030445 non-null object
Campaign                       106109 non-null object
Targ/aud/pin                   106109 non-null object
Keyword                        79772 non-null object
Start Date                     106109 non-null object
MAID                           106109 non-null object
Video v Static                 106109 non-null object
Impressions with Video View    106109 non-null float64
Week Start                     106109 non-null object
Reporting Month                106109 non-null object
Reporting Period               106109 non-null object
Placement                      106109 non-null object
Creative              

### Aggregate data by 'Week Start'

In [12]:
bp_aug_weekly = bp_aug.groupby(['Week Start']).mean()

In [14]:
bp_aug_weekly

Impressions with Video View   Impressions      Clicks  \
Week Start                                                          
7/16/18                     3284.413213   5939.901783   33.220451   
7/23/18                     4239.107403  13812.365696  183.851224   
7/30/18                     1326.813507   3273.092256   34.854358   
8/13/18                      668.515327   3668.967409   39.086231   
8/20/18                      311.999585   3749.428055   48.109058   
8/27/18                      434.154125   1940.833231   28.829348   
8/6/18                      1566.570049   4441.252399   44.966572   

                  Views  Completed Views  Conversions    Sessions  \
Week Start                                                          
7/16/18      868.709548       227.094872     2.394040   20.498367   
7/23/18     1172.979488       354.336509     3.272476  102.465615   
7/30/18      358.720686        42.288757     2.924332   22.051954   
8/13/18      183.498206        37.226760     2.017387   24.616918   
8/20/18       76.802883        42.661312     9.607782   26.823648   
8/27/18      124.768021        75.163874    15.360512   18.767685   
8/6/18       405.607228        63.797399     2.180188   29.351353   

            New Sessions     Bounce  Register  Subscribe  
Week Start                                                
7/16/18        18.459432  16.542828  0.239136   0.016076  
7/23/18        86.301982  90.106998  0.338390   0.027710  
7/30/18        17.426327  18.936493  0.084533   0.009704  
8/13/18        17.075068  19.679640  0.186179   0.011247  
8/20/18        17.393460  21.456193  0.186067   0.011255  
8/27/18        12.935343  14.589707  0.221721   0.016609  
8/6/18         21.100246  24.541082  0.164760   0.015006

In [16]:
bp_aug_weekly.to_csv('bp_aug_weekly.csv')